---
layout: default
title: Inizio del progetto - creazione errori
---

Per iniziare la parte di gestione errori bisogna installare `express` e i suoi `tipi`

``` bash
npm install express class-validator
npm install --save-dev @types/express
```

Adesso partiamo creando gli errori

``` bash
mkdir src/errors
touch src/errors/internal-server-error.ts
touch src/errors/not-found.ts
touch src/errors/dotenv.ts
touch src/errors/custom.ts
touch src/errors/unouthorized.ts
touch src/errors/validation.ts
touch src/errors/user-exist.ts
touch src/errors/index.ts
```


Adesso che abbiamo una buona base, iniziamo con il capire come funziona tutta la parte della gestione errori, iniziamo con il creare il classicissimo errore 404 (not found)

``` ts
import { Request, Response, NextFunction } from "express";

export class NotFoundError extends Error {
  constructor(entity?: string) {
    super(`Entity ${entity} not found`);
    this.name = "NotFoundError";
    Object.setPrototypeOf(this, NotFoundError.prototype);
  }
}

export const notFoundHandler = (err: Error, req: Request, res: Response, next: NextFunction) => {
  if (err instanceof NotFoundError) {
    res.status(404).json({
      error: err.name,
      message: err.message
    });
  } else {
    next(err);
  }
};
```

Dopo aver creato questo file bisogna inserirlo nel file `index.ts` (quello degli errori che abbiamo appena creato)

``` ts
import { notFoundHandler } from "./not-found";

export const errorHandlers = [
    notFoundHandler
]
```

##### Capiamo il funzionamento dei file appena creati

Adesso capiamo come funziona e soprattutto perché funziona. Nel file `not-found.ts` abbiamo esportato 2 elementi: una `constante` e una `classe`, la classe è quella che andrai a richiamare dovunque ti serva richiamare questo specifico errore, ad esempio così

``` ts
throw new NotFoundError(entity);
```

Cosa fa `super()`? La parola chiave `super()` in TypeScript (e JavaScript) viene usata per **chiamare il costruttore della classe padre**, ovvero la classe da cui stai estendendo.

##### Effetto:
- Imposta il messaggio dell'errore (`err.message`)
- Permette al motore JavaScript/TypeScript di gestire lo stack trace correttamente
- Ti consente di accedere a metodi/attributi di `Error`

##### Quindi questa riga:

``` ts
super(`Entity ${entity} not found`);
```

Equivale a scrivere la riga qui sotto ma all'interno della tua sottoclasse personalizzata. :

``` ts
const error = new Error(`Entity ${entity} not found`);
```

Quando estendi `Error`, è buona pratica anche aggiungere:

``` ts
Object.setPrototypeOf(this, NotFoundError.prototype);
```

Per garantire che `instanceof` funzioni correttamente, specialmente in ambienti JavaScript transpiled (come quando usi `tsc`). questo garantisce che funzioni correttamente quando chiami l'instanza ad esempio quando in un controller controlli di che tipo è l'errore, se entra nel blocco else `next()` si occupa di scorrere tutti gli errori dentro `index.ts` che poi collegheremo in `app.ts` e controlla tutte le istanze fino a trovare quella corretta, quindi in `errorHandlers` gli errori vanno messi a livello di importanza dal più restrittivo al più generico. il più generico di solito è `internal server error` con status code `500` che indica che l'errore generato non è stato gestito da nessun `middleware`. In quel caso bisogna trovare dove viene generato l'errore e tipizzarlo.

``` ts
if(err instanceof NotFoundError) {/*Fai qualcosa*/} 
```

Adesso che abbiamo capito a cosa serve la classe vediamo a cosa serve la costante `notFoundHandler`, semplicemente si occupa di catturare tutti gli errori di tipo `NotFoundError` e impostare l'errore con il `name` e il `message` che abbiamo nel `constructor`, ricordiamo che `message` non lo dichiariamo direttamente ma lo fa `super()` dietro le quinte. Adesso che abbiamo capito come funziona tutta la logica di gestione degli errori (`middleware`) creiamo tutti gli errori che ci servono.

#### Errori di base

##### `Unouthorized error`

``` ts
import { Request, Response, NextFunction } from "express";

export class UnauthorizedError extends Error {
  constructor(message = "User not authorized") {
    super(message);
    this.name = "UnauthorizedError";
    Object.setPrototypeOf(this, UnauthorizedError.prototype);
  }
}

export const unauthorizedHandler = (
  err: Error,
  req: Request,
  res: Response,
  next: NextFunction
) => {
  if (err instanceof UnauthorizedError) {
    res.status(401).json({
      error: err.name,
      message: err.message
    });
  } else {
    next(err);
  }
};
```

##### `Dotenv error`

``` ts
import { Request, Response, NextFunction } from "express";

export class DotEnvError extends Error {
  constructor(entity?: string) {
    super(`Entity ${entity} not found in dotenv`);
    this.name = "DotEnvError";
    Object.setPrototypeOf(this, DotEnvError.prototype);
  }
}

export const dotenvHandler = (err: Error, req: Request, res: Response, next: NextFunction) => {
  if (err instanceof DotEnvError) {
    res.status(404).json({
      error: err.name,
      message: err.message
    });
  } else {
    next(err);
  }
};
```


##### `Custom error`

``` ts
import { Request, Response, NextFunction } from "express";

export class CustomError extends Error {
  statusCode: number;
  constructor(
    name: string = "CustomError",
    message: string = "Custom error message",
    statusCode: number = 400
  ) {
    if (!Number.isInteger(statusCode) || statusCode < 100 || statusCode > 599) {
      throw new RangeError(
        `Invalid HTTP status code: ${statusCode}. It must be an integer between 100 and 599.`
      );
    }
  
    super(message);
    this.name = name;
    this.statusCode = statusCode;
    Object.setPrototypeOf(this, CustomError.prototype);
  }
}

export const customHandler = (err: Error, req: Request, res: Response, next: NextFunction) => {
  if (err instanceof CustomError) {
    res.status(err.statusCode).json({
      error: err.name,
      message: err.message
    });
  } else {
    next(err);
  }
};
```

##### Attenzione!

Per quanto riguarda il `custom error` è importante chiarire che DEVE essere usato solo per messaggi poco importanti, perché se te vai a controllare l'instanza dell'errore non ci trovi l'istanza dell'errore che vuoi scatenare ma una generica.

##### `Internal server error`

``` ts
import { Request, Response, NextFunction } from "express";

export const internalServerErrorHandler = (
  err: Error,
  req: Request,
  res: Response,
  next: NextFunction
) => {
  console.error(err);
  res.status(500).json({
    error: "InternalServerError",
    message: "The server encountered an internal error. Err: " + err.message
  });
};
```

Errore che viene richiamato dopo aver controllato tutti gli altri `middleware` come detto prima

##### `User exist error`

``` ts
import { Request, Response, NextFunction } from "express";

export class UserExistsError extends Error {
  constructor(username: string) {
    super(`username ${username} already in use`);
    this.name = "UserExists";
    Object.setPrototypeOf(this, UserExistsError.prototype);
  }
}

export const userExistHandler = (err: Error, req: Request, res: Response, next: NextFunction) => {
  if (err instanceof UserExistsError) {
    res.status(409).json({
      error: err.name,
      message: err.message
    });
  } else {
    next(err);
  }
};
```


##### `Validation error`

``` ts
import { NextFunction, Request, Response } from "express";
import { ValidationError as OriginalValidationError } from "class-validator";

export class ValidationError extends Error {
  originalErrors: OriginalValidationError[];

  constructor(errors: OriginalValidationError[]) {
    const message = errors.map((err) => Object.values(err.constraints ?? {}).join(", ")).join("; ");

    super(message);
    this.originalErrors = errors;
    this.name = "ValidationError";
    Object.setPrototypeOf(this, ValidationError.prototype);
  }
}

export const validationErrorHandler = async (
  err: Error,
  req: Request,
  res: Response,
  next: NextFunction
) => {
  if (err instanceof ValidationError) {
    res.status(400).json({
      error: err.name,
      message: err.message,
      details: err.originalErrors.map((e) => ({
        property: e.property,
        constraints: e.constraints,
        value: e.value
      }))
    });
  } else {
    next(err);
  }
};
```

###### Menzione speciale per `ValidationError` 

`ValidationError` è un `middleware`  dedicato per gestire gli errori di `class-validator` che metteremo nei `dto`.  Questa sezione del codice la vedremo più avanti, ma intanto è importante capire come vengono gestiti gli errori di `class-validator` e formattarli al meglio.

##### Adesso che abbiamo creato tutti gli errori mettiamoli nel file `index.ts`

``` ts
import { customErrorHandler } from "./custom";
import { dotenvErrorHandler } from "./dotenv";
import { internalServerErrorHandler } from "./internal-server-error";
import { notFoundErrorHandler } from "./not-found";
import { unauthorizedErrorHandler } from "./unauthorized";
import { userExistErrorHandler } from "./user-exist";
import { validationErrorHandler } from "./validation";

/* Gli errori vanno messi in ordine di importanza dal piu restrittivo al piu generico */

export const errorHandlers = [
  customErrorHandler,
  validationErrorHandler,
  notFoundErrorHandler,
  dotenvErrorHandler,
  unauthorizedErrorHandler,
  userExistErrorHandler,

  // Internal server error
  internalServerErrorHandler
];
```

